In [2]:
#PANDAS 
#NUMPY
#MATPLOTLIB
#SEABORN 


In [4]:
import pandas as pd
pd.set_option("display.max_columns",500)
pd.set_option("display.max_rows",500)

In [2]:
#conda install pandas

In [3]:
ls

 Volume in drive C is Windows
 Volume Serial Number is AE0D-904C

 Directory of C:\Users\Suhas\Desktop\python somenath

16-12-2022  15:28    <DIR>          .
08-12-2022  15:33    <DIR>          ..
15-12-2022  13:15    <DIR>          .ipynb_checkpoints
15-12-2022  08:37                 8 .Rhistory
09-12-2022  08:57            72,894 DA 7th Sep 7-9.ipynb
12-12-2022  13:13    <DIR>          Data Sets
12-12-2022  07:59             1,336 mtcars.csv
16-12-2022  13:01            94,716 native python.ipynb
13-12-2022  17:51           239,612 numpy and plot.ipynb
16-12-2022  15:28           336,151 Pandas_Introduction.ipynb
14-12-2022  08:42             1,401 practice r
12-12-2022  13:19         1,093,227 Python_for_You_and_Me textbook.pdf
               8 File(s)      1,839,345 bytes
               4 Dir(s)  452,824,100,864 bytes free


In [5]:
df=pd.read_csv("mtcars.csv")


In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [8]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [10]:
df.shape

(32, 11)

In [11]:
df.tail(3)

mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
29  19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
30  15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
31  21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [12]:
df.sample(3)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1

In [13]:
df.columns


Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [14]:
df.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [11]:
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64  
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64  
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64  
 8   am      32 non-null     int64  
 9   gear    32 non-null     int64  
 10  carb    32 non-null     int64  
dtypes: float64(5), int64(6)
memory usage: 2.9 KB


In [17]:
df.isna()

mpg    cyl   disp     hp   drat     wt   qsec     vs     am   gear  \
0   False  False  False  False  False  False  False  False  False  False   
1   False  False  False  False  False  False  False  False  False  False   
2   False  False  False  False  False  False  False  False  False  False   
3   False  False  False  False  False  False  False  False  False  False   
4   False  False  False  False  False  False  False  False  False  False   
5   False  False  False  False  False  False  False  False  False  False   
6   False  False  False  False  False  False  False  False  False  False   
7   False  False  False  False  False  False  False  False  False  False   
8   False  False  False  False  False  False  False  False  False  False   
9   False  False  False  False  False  False  False  False  False  False   
10  False  False  False  False  False  False  False  False  False  False   
11  False  False  False  False  False  False  False  False  False  False   
12  False  False  False  False  False  False  False  False  False  False   
13  False  False  False  False  False  False  False  False  False  False   
14  False  False  False  False  False  False  False  False  False  False   
15  False  False  False  False  False  False  False  False  False  False   
16  False  False  False  False  False  False  False  False  False  False   
17  False  False  False  False  False  False  False  False  False  False   
18  False  False  False  False  False  False  False  False  False  False   
19  False  False  False  False  False  False  False  False  False  False   
20  False  False  False  False  False  False  False  False  False  False   
21  False  False  False  False  False  False  False  False  False  False   
22  False  False  False  False  False  False  False  False  False  False   
23  False  False  False  False  False  False  False  False  False  False   
24  False  False  False  False  False  False  False  False  False  False   
25  False  False  False  False  False  False  False  False  False  False   
26  False  False  False  False  False  False  False  False  False  False   
27  False  False  False  False  False  False  False  False  False  False   
28  False  False  False  False  False  False  False  False  False  False   
29  False  False  False  False  False  False  False  False  False  False   
30  False  False  False  False  False  False  False  False  False  False   
31  False  False  False  False  False  False  False  False  False  False   

     carb  
0   False  
1   False  
2   False  
3   False  
4   False  
5   False  
6   False  
7   False  
8   False  
9   False  
10  False  
11  False  
12  False  
13  False  
14  False  
15  False  
16  False  
17  False  
18  False  
19  False  
20  False  
21  False  
22  False  
23  False  
24  False  
25  False  
26  False  
27  False  
28  False  
29  False  
30  False  
31  False

In [18]:
df.isna().sum()

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [19]:
df.min()

mpg     10.400
cyl      4.000
disp    71.100
hp      52.000
drat     2.760
wt       1.513
qsec    14.500
vs       0.000
am       0.000
gear     3.000
carb     1.000
dtype: float64

In [20]:
df.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [21]:
df.var()

mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64

In [22]:
df.std()

mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

In [23]:
df.quantile([0.50,0.25,0.75,0.82,1,])

mpg  cyl     disp     hp   drat       wt     qsec   vs   am  gear  \
0.50  19.200  6.0  196.300  123.0  3.695  3.32500  17.7100  0.0  0.0   4.0   
0.25  15.425  4.0  120.825   96.5  3.080  2.58125  16.8925  0.0  0.0   3.0   
0.75  22.800  8.0  326.000  180.0  3.920  3.61000  18.9000  1.0  1.0   4.0   
0.82  25.072  8.0  354.780  209.2  4.080  3.80520  19.4526  1.0  1.0   4.0   
1.00  33.900  8.0  472.000  335.0  4.930  5.42400  22.9000  1.0  1.0   5.0   

      carb  
0.50   2.0  
0.25   2.0  
0.75   4.0  
0.82   4.0  
1.00   8.0

In [24]:
df.vs.value_counts()

0    18
1    14
Name: vs, dtype: int64

In [13]:
df.cyl.value_counts()

8    14
4    11
6     7
Name: cyl, dtype: int64

In [25]:
df.gear.value_counts()

3    15
4    12
5     5
Name: gear, dtype: int64

# how to select specific columns in data

In [26]:
df[['mpg','hp']]

mpg   hp
0   21.0  110
1   21.0  110
2   22.8   93
3   21.4  110
4   18.7  175
5   18.1  105
6   14.3  245
7   24.4   62
8   22.8   95
9   19.2  123
10  17.8  123
11  16.4  180
12  17.3  180
13  15.2  180
14  10.4  205
15  10.4  215
16  14.7  230
17  32.4   66
18  30.4   52
19  33.9   65
20  21.5   97
21  15.5  150
22  15.2  150
23  13.3  245
24  19.2  175
25  27.3   66
26  26.0   91
27  30.4  113
28  15.8  264
29  19.7  175
30  15.0  335
31  21.4  109

In [27]:

# selecting only one column
df["mpg"]
df.mpg
df[["mpg"]]

# selecting multiple columns

df[["mpg","hp"]]


mpg   hp
0   21.0  110
1   21.0  110
2   22.8   93
3   21.4  110
4   18.7  175
5   18.1  105
6   14.3  245
7   24.4   62
8   22.8   95
9   19.2  123
10  17.8  123
11  16.4  180
12  17.3  180
13  15.2  180
14  10.4  205
15  10.4  215
16  14.7  230
17  32.4   66
18  30.4   52
19  33.9   65
20  21.5   97
21  15.5  150
22  15.2  150
23  13.3  245
24  19.2  175
25  27.3   66
26  26.0   91
27  30.4  113
28  15.8  264
29  19.7  175
30  15.0  335
31  21.4  109

In [28]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

# loc/ iloc

In [29]:
df.head(4)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [30]:
df.loc[[0,1,2],["mpg","cyl","disp","hp"]]

mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93

In [14]:
df.loc[1:3,"disp":"wt"]

disp   hp  drat     wt
1  160.0  110  3.90  2.875
2  108.0   93  3.85  2.320
3  258.0  110  3.08  3.215

In [15]:
df.loc[2:3,"qsec":"carb"]

qsec  vs  am  gear  carb
2  18.61   1   1     4     1
3  19.44   1   0     3     1

In [16]:
df.iloc[0:3,0:4]

mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93

In [34]:
#df.loc
#df.iloc

df.loc[[0,1,2],["mpg","cyl","disp","hp"]]

df.iloc[0:3,0:4]


mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93

In [35]:
df.loc[0:3,["mpg","cyl","disp","hp"]]

mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93
3  21.4    6  258.0  110

In [36]:
df.iloc[0:3,0:5]

mpg  cyl   disp   hp  drat
0  21.0    6  160.0  110  3.90
1  21.0    6  160.0  110  3.90
2  22.8    4  108.0   93  3.85

In [17]:
df.loc[22:24:2,:]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2

In [38]:
df.iloc[21:28:4,:]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1

In [39]:
# df.loc
# df.iloc

df.loc[[0,1,3],["mpg","cyl","hp"]]



mpg  cyl   hp
0  21.0    6  110
1  21.0    6  110
3  21.4    6  110

In [40]:
df.iloc[3,5]

3.215

In [41]:
df.iloc[[0,1,2,4],0:4]

mpg  cyl   disp   hp
0  21.0    6  160.0  110
1  21.0    6  160.0  110
2  22.8    4  108.0   93
4  18.7    8  360.0  175

In [42]:
df.loc[22:24,["mpg","cyl","qsec"]]

mpg  cyl   qsec
22  15.2    8  17.30
23  13.3    8  15.41
24  19.2    8  17.05

In [43]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

# filter 

In [44]:
df[df['hp']>200]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8

In [45]:
df[df["gear"]==5]

mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
26  26.0    4  120.3   91  4.43  2.140  16.7   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8

In [46]:
df[(df["mpg"]>15)&(df["gear"]>4)]



mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
26  26.0    4  120.3   91  4.43  2.140  16.7   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6

In [47]:
df[(df["gear"]==4)| (df["mpg"]>22) | (df["wt"]>2) ]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [48]:
df[(df["gear"]==4)|(df["gear"]==3)]

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

# group by using pandas 

In [28]:
for idx,data in df.groupby(["gear"]):
    print("ID of the group ::: ",idx)


    print("data of the group ==> \n",data)
    print("=="*20)

ID of the group :::  3
data of the group ==> 
      mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.

In [50]:
for idx,data in df.groupby(["gear","cyl"]):
    print("ID of the group ::: ",idx)


    print("data of the group ==> \n",data)
    print("=="*20)

ID of the group :::  (3, 4)
data of the group ==> 
      mpg  cyl   disp  hp  drat     wt   qsec  vs  am  gear  carb
20  21.5    4  120.1  97   3.7  2.465  20.01   1   0     3     1
ID of the group :::  (3, 6)
data of the group ==> 
     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
5  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
ID of the group :::  (3, 8)
data of the group ==> 
      mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0    

In [35]:
df.groupby(["gear"])["mpg"].mean()

gear
3    16.106667
4    24.533333
5    21.380000
Name: mpg, dtype: float64

In [52]:
df.groupby(["gear","cyl"])["mpg"].describe()

count    mean       std   min     25%    50%     75%   max
gear cyl                                                            
3    4      1.0  21.500       NaN  21.5  21.500  21.50  21.500  21.5
     6      2.0  19.750  2.333452  18.1  18.925  19.75  20.575  21.4
     8     12.0  15.050  2.774396  10.4  14.050  15.20  16.625  19.2
4    4      8.0  26.925  4.807360  21.4  22.800  25.85  30.900  33.9
     6      4.0  19.750  1.552417  17.8  18.850  20.10  21.000  21.0
5    4      2.0  28.200  3.111270  26.0  27.100  28.20  29.300  30.4
     6      1.0  19.700       NaN  19.7  19.700  19.70  19.700  19.7
     8      2.0  15.400  0.565685  15.0  15.200  15.40  15.600  15.8

In [53]:
df.groupby(["gear","cyl"])[["mpg"]].agg({"mean","count","std","var","max","median","quantile"})




mpg                                                
         quantile       std   max median    mean count        var
gear cyl                                                         
3    4      21.50       NaN  21.5  21.50  21.500     1        NaN
     6      19.75  2.333452  21.4  19.75  19.750     2   5.445000
     8      15.20  2.774396  19.2  15.20  15.050    12   7.697273
4    4      25.85  4.807360  33.9  25.85  26.925     8  23.110714
     6      20.10  1.552417  21.0  20.10  19.750     4   2.410000
5    4      28.20  3.111270  30.4  28.20  28.200     2   9.680000
     6      19.70       NaN  19.7  19.70  19.700     1        NaN
     8      15.40  0.565685  15.8  15.40  15.400     2   0.320000

In [54]:
df.groupby(["cyl","gear","vs"])[["mpg"]].mean()

mpg
cyl gear vs        
4   3    1   21.500
    4    1   26.925
    5    0   26.000
         1   30.400
6   3    1   19.750
    4    0   21.000
         1   18.500
    5    0   19.700
8   3    0   15.050
    5    0   15.400

In [55]:
#group by 
df.groupby(["gear","vs"])["mpg"].describe()

count       mean       std   min    25%    50%     75%   max
gear vs                                                              
3    0    12.0  15.050000  2.774396  10.4  14.05  15.20  16.625  19.2
     1     3.0  20.333333  1.934770  18.1  19.75  21.40  21.450  21.5
4    0     2.0  21.000000  0.000000  21.0  21.00  21.00  21.000  21.0
     1    10.0  25.240000  5.540999  17.8  21.75  23.60  29.625  33.9
5    0     4.0  19.125000  5.022201  15.0  15.60  17.75  21.275  26.0
     1     1.0  30.400000       NaN  30.4  30.40  30.40  30.400  30.4

In [56]:
pd.DataFrame([[1,2],[3,4]],columns=["a","b"],index=["a","b"])

a  b
a  1  2
b  3  4

# how to add / delete a col

In [57]:
df["new_col"]=1

In [36]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [41]:
#add a new column
l=[]
for i in df["gear"]:
    if i%2==0:
        l.append("even")
    else:
        l.append("odd")
df["new_col"] =l   
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb new_col  \
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4    even   
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4    even   
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1    even   
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1     odd   
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2     odd   
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1     odd   
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4     odd   
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2    even   
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2    even   
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4    even   
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4    even   
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3     odd   
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3     odd   
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3     odd   
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4     odd   
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4     odd   
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4     odd   
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1    even   
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2    even   
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1    even   
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1     odd   
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2     odd   
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2     odd   
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4     odd   
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2     odd   
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1    even   
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2     odd   
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2     odd   
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4     odd   
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6     odd   
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8     odd   
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2    even   

    new_col3  
0       True  
1       True  
2       True  
3       True  
4      False  
5      False  
6      False  
7       True  
8       True  
9      False  
10     False  
11     False  
12     False  
13     False  
14     False  
15     False  
16     False  
17      True  
18      True  
19      True  
20      True  
21     False  
22     False  
23     False  
24     False  
25      True  
26      True  
27      True  
28     False  
29     False  
30     False  
31      True

In [43]:
l=[]
for i in df["vs"]:
    if i==0:
        l.append("zero")
    else:
        l.append("non_zero")
df["new_col2"] =l   
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb new_col  \
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4    even   
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4    even   
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1    even   
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1     odd   
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2     odd   
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1     odd   
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4     odd   
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2    even   
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2    even   
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4    even   
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4    even   
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3     odd   
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3     odd   
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3     odd   
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4     odd   
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4     odd   
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4     odd   
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1    even   
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2    even   
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1    even   
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1     odd   
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2     odd   
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2     odd   
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4     odd   
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2     odd   
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1    even   
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2     odd   
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2     odd   
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4     odd   
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6     odd   
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8     odd   
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2    even   

    new_col3  new_col2  
0       True      zero  
1       True      zero  
2       True  non_zero  
3       True  non_zero  
4      False      zero  
5      False  non_zero  
6      False      zero  
7       True  non_zero  
8       True  non_zero  
9      False  non_zero  
10     False  non_zero  
11     False      zero  
12     False      zero  
13     False      zero  
14     False      zero  
15     False      zero  
16     False      zero  
17      True  non_zero  
18      True  non_zero  
19      True  non_zero  
20      True  non_zero  
21     False      zero  
22     False      zero  
23     False      zero  
24     False      zero  
25      True  non_zero  
26      True      zero  
27      True  non_zero  
28     False      zero  
29     False      zero  
30     False      zero  
31      True  non_zero

In [44]:
df["new_col3"]=df["mpg"]>=20

In [45]:
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb new_col  \
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4    even   
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4    even   
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1    even   
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1     odd   
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2     odd   
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1     odd   
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4     odd   
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2    even   
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2    even   
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4    even   
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4    even   
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3     odd   
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3     odd   
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3     odd   
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4     odd   
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4     odd   
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4     odd   
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1    even   
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2    even   
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1    even   
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1     odd   
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2     odd   
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2     odd   
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4     odd   
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2     odd   
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1    even   
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2     odd   
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2     odd   
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4     odd   
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6     odd   
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8     odd   
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2    even   

    new_col3  new_col2  
0       True      zero  
1       True      zero  
2       True  non_zero  
3       True  non_zero  
4      False      zero  
5      False  non_zero  
6      False      zero  
7       True  non_zero  
8       True  non_zero  
9      False  non_zero  
10     False  non_zero  
11     False      zero  
12     False      zero  
13     False      zero  
14     False      zero  
15     False      zero  
16     False      zero  
17      True  non_zero  
18      True  non_zero  
19      True  non_zero  
20      True  non_zero  
21     False      zero  
22     False      zero  
23     False      zero  
24     False      zero  
25      True  non_zero  
26      True      zero  
27      True  non_zero  
28     False      zero  
29     False      zero  
30     False      zero  
31      True  non_zero

In [46]:
df.drop(["new_col","new_col2","new_col3"],axis=1,inplace=True)


In [47]:
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [48]:
df.drop([0],axis=0,inplace=True)

In [49]:
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1

# sorting the data

In [50]:
df=pd.read_csv("mtcars.csv")


In [51]:
df.sort_values(["hp"],ascending=[False])

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2

In [52]:
df.sort_values(["mpg","hp"],ascending=[False,True])

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4

# numpy intro

In [1]:
import numpy as np
#pip install numpy
#!pip install numpy
#conda install numpy

In [2]:
l=[[1,2],
   [2,3]]

In [3]:
type(l)

list

In [4]:
l+l

[[1, 2], [2, 3], [1, 2], [2, 3]]

In [5]:
a=np.array(l)
b=np.array([[4,5],
            [7,8]])

In [6]:
type(a)

numpy.ndarray

In [7]:
a

array([[1, 2],
       [2, 3]])

In [8]:
a.shape

(2, 2)

In [9]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a

array([[1, 2],
       [2, 3]])

In [63]:
b

array([[4, 5],
       [7, 8]])

In [64]:
a+b

array([[ 5.,  6.],
       [ 9., 11.]])

In [65]:
a-b

array([[-3., -4.],
       [-5., -5.]])

In [66]:
a+1

array([[2., 2.],
       [3., 4.]])

In [67]:
a*2

array([[2., 2.],
       [4., 6.]])

In [68]:
a**2

array([[1., 1.],
       [4., 9.]])

In [51]:
a

array([[1, 2],
       [2, 3]])

In [52]:
b

array([[4, 5],
       [7, 8]])

In [53]:
b.T

array([[4, 7],
       [5, 8]])

In [54]:
a*b

array([[ 4, 10],
       [14, 24]])

In [ ]:
A-->(p,m) B ---> (m,n)

#number of col of A === number of rowa of B


In [21]:
np.dot(a,b)

array([[18, 21],
       [29, 34]])

In [20]:
np.matmul(a,b)

array([[18, 21],
       [29, 34]])

In [55]:
a

array([[1, 2],
       [2, 3]])

In [32]:
b=np.linalg.inv(a)

In [34]:
b

array([[-3.,  2.],
       [ 2., -1.]])

In [33]:
np.dot(a,b)

array([[1., 0.],
       [0., 1.]])

In [104]:
np.cos(3.14/2)

0.0007963267107332633

In [189]:
np.tan(22/7)

0.0012644899412945707

In [105]:
np.exp(1) #e^10

2.718281828459045

In [43]:
np.pi

3.141592653589793

In [18]:

#2^x=32

np.log2(32)

5.0

In [163]:
a

array([[1, 2],
       [2, 3]])

a[start:end:step,start:end:step]

In [167]:
a[::-1,:]

array([[2, 3],
       [1, 2]])

In [99]:
a

array([[1, 2],
       [2, 3]])

In [189]:
b

array([[4, 5],
       [7, 8]])

In [110]:
np.sum(b,axis=1)

array([ 9, 15])

In [99]:
a

array([[1, 2],
       [2, 3]])

In [49]:
np.median(a)

2.0

In [50]:

np.median(b,axis=1)

array([4.5, 7.5])

In [89]:
a

array([[1, 2],
       [2, 3]])

In [90]:
np.concatenate([a,a],axis=0)

array([[1, 2],
       [2, 3],
       [1, 2],
       [2, 3]])

In [91]:
np.concatenate([a,a],axis=1)

array([[1, 2, 1, 2],
       [2, 3, 2, 3]])

In [111]:
l=[[1,2,3],[3,4,5],[3,6,7]]
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [3, 6, 7]])

In [112]:
np.sum(l,axis=0)

array([ 7, 12, 15])

In [113]:
np.sum(l,axis=1)

array([ 6, 12, 16])

# inverse 


In [ ]:
ope---> +
identity=0 #5+0=5 10+0=10
a+b=0
b = -a


ope---->*
identity=1 # 5*1=5 10*1=10
a*b=1 
b=1/a


ope-->matmul

identity= np.array([[1,0],[0,1]])   # a*iden=a


inv= a*b =identity

In [114]:
a

array([[1, 2],
       [2, 3]])

In [115]:
b=np.array([[1,0],[0,1]])

In [151]:
np.matmul(a,b) 

array([[1, 2],
       [2, 3]])

In [153]:
ainv=np.linalg.inv(a)

In [154]:
a

array([[1, 2],
       [2, 3]])

In [155]:
ainv

array([[-3.,  2.],
       [ 2., -1.]])

In [156]:
np.matmul(a,ainv)

array([[1., 0.],
       [0., 1.]])

In [157]:
a

array([[1, 2],
       [2, 3]])

In [158]:
b

array([[1, 0],
       [0, 1]])

In [ ]:
1 2
2 3

In [159]:
b

array([[1, 0],
       [0, 1]])

In [161]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# index 

In [ ]:
list,str,tuple,np.array,dataframe

In [69]:
a=[6,23,90,56,23,12,78,99,232]
#a[start:end:step]

In [88]:
a[::-1]

[232, 99, 78, 12, 23, 56, 90, 23, 6]

In [72]:
a[1:]

[23, 90, 56, 23, 12, 78, 99, 232]

In [73]:
a[:4]

[6, 23, 90, 56]

In [76]:
a[1:4:1]

[23, 90, 56]

In [77]:
a[1:4:2]

[23, 56]

In [27]:
a[1:4:3]

[23]

In [175]:
a[4:1:-1]

[78, 12, 23]

In [41]:
a="python"


In [42]:
a[1:4:1]

'yth'

In [182]:
a="hjh"
a==a[::-1]

True

In [183]:
fun =lambda a: a==a[::-1]

In [184]:
fun("mom")

True

In [185]:
fun("jhbfhed")

False

In [93]:
def fun(x):
    
    if x==x[::-1]:
        return True
    else:
        return False

In [95]:
fun("mom")

True

In [91]:
a="dad"

In [92]:
a[::-1]

'dad'